### PR TITLE
Complexity of Lists

### PR DESCRIPTION
**Pull request by VladimirAlexiev**
@azaroth42 see section Complexity of Lists

### CODE REVIEW

**Comment by VladimirAlexiev** [comment]
@azaroth42 Furthermore, a query like
`?object crm:P62_depicts/(rdf:rest*/rdf:first)? ?person`
does not guarantee in what order it will return `?person`.

See https://github.com/eclipse/rdf4j/issues/695#issuecomment-266994185 for some discussion how sophisticated path rewriting can return shortest paths first... but this is not yet implemented in rdf4j.

(@workergnome please add the above text to the page)

**Comment by azaroth42** [comment]
As the PR is just updating your views, it seems fine to me. I disagree with those views, but that's no reason to not merge :)  [I also don't have write access, so can't merge]

**Comment by workergnome** [comment]
Merged.

**Comment by VladimirAlexiev** [comment]
@azaroth42 you can comment and express your views

**Pull request merged**
